version: "3.8"
services:
  postgres-db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: users_postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-db-data:/var/lib/postgresql/data

  mysql-db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: users_mysql
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    ports:
      - "3306:3306"
    volumes:
      - mysql-db-data:/var/lib/mysql

  user-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-service
    depends_on:
      - postgres-db
      - mysql-db
    ports:
      - "8080:8080"

volumes:
  postgres-db-data:
  mysql-db-data:
